#!/usr/bin/env node

/**
 * Version Sync Script
 * 
 * This script synchronizes version numbers across the codebase.
 * It reads the version from package.json and updates all other files.
 */

const fs = require('fs');
const path = require('path');

// Root directory
const rootDir = path.resolve(__dirname, '..');

// Read version from package.json
const packageJsonPath = path.join(rootDir, 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

console.log(`📌 Synchronizing version to ${version}...`);

// Update the version.ts file
const versionFilePath = path.join(rootDir, 'src', 'config', 'version.ts');
let versionContent = `// This file is generated automatically from package.json
// Do not edit this file directly

export const VERSION: string = "${version}"; // Auto-generated on ${new Date().toISOString()}
`;

fs.writeFileSync(versionFilePath, versionContent, 'utf8');
console.log(`✅ Updated ${versionFilePath}`);

// Update manifest.json
const manifestPath = path.join(rootDir, 'src', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
manifest.version = version;
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
console.log(`✅ Updated ${manifestPath}`);

console.log(`\n🎉 Successfully synchronized version ${version} across all files!`);
console.log(`\nReminder: Run this script whenever you update the version in package.json`);
